# Development Profile

spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus_events?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=0531

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.com.smartcampus=DEBUG
